name: Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
  workflow_run:
    workflows: ["Presubmit"]
    types:
      - completed

jobs:
  automerge-check:
    runs-on: ubuntu-latest
    steps:
    - uses: machine-learning-apps/actions-app-token@master
      id: get_token
      with:
        APP_PEM: ${{ secrets.APP_PEM }}
        APP_ID: ${{ secrets.APP_ID }}
    - name: automerge-check
      uses: "pascalgn/automerge-action@v0.8.5"
      with:
        args: "--trace"
      env:
        GITHUB_TOKEN: "${{ steps.get_token.outputs.app_token }}"
        MERGE_LABELS: "automerge"
        MERGE_REMOVE_LABELS: "automerge"
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
        MERGE_FORKS: "false"
        UPDATE_LABELS: "automerge"
        UPDATE_METHOD: "merge"

