name: Presubmit

on:
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - run: env

  build-mac:
    runs-on: macos-latest
    steps:
    - run: env

  build-win:
    runs-on: windows-2019
    steps:
    - run: ls

  test:
    needs:
    - build-linux
    - build-mac
    - build-win
    runs-on: ubuntu-latest
    steps:
    - uses: machine-learning-apps/actions-app-token@master
      id: get_token
      with:
        APP_PEM: ${{ secrets.APP_PEM }}
        APP_ID: ${{ secrets.APP_ID }}
    - run: |
        echo "::set-env name=GITHUB_TOKEN::${{ steps.get_token.outputs.app_token }}"
        env
        sleep 30
